# cloudbuild.yaml
steps:
# 1. Build the Docker image and tag it using the commit SHA
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'us-central1-docker.pkg.dev/stackops-backend-475222/stackops-repo/stackops-app:$COMMIT_SHA', 
    '.'
  ]

# 2. Push the newly tagged image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'us-central1-docker.pkg.dev/stackops-backend-475222/stackops-repo/stackops-app:$COMMIT_SHA'
  ]

# 3. Deploy the new image to Cloud Run
# It relies on the existing service configuration for env vars, secrets, and SQL connection.
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run',
    'deploy',
    'stackops-backend',
    '--image', 'us-central1-docker.pkg.dev/stackops-backend-475222/stackops-repo/stackops-app:$COMMIT_SHA',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--quiet'
  ]

timeout: '1600s'

# Store the final deployed image in the Artifact Registry
images:
- 'us-central1-docker.pkg.dev/stackops-backend-475222/stackops-repo/stackops-app:$COMMIT_SHA'