[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Serve static files
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200