CREATE TABLE IF NOT EXISTS StackCTRLIntelligenceSchedules (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CompanyID BIGINT NOT NULL,
    ScheduleKey VARCHAR(100) NOT NULL,
    ScheduleType VARCHAR(50) NOT NULL,
    CronExpression VARCHAR(100) NOT NULL,
    TimeZone VARCHAR(100) NOT NULL DEFAULT 'Africa/Johannesburg',
    BusinessDaysJson JSON NULL,
    BusinessStartTime TIME NULL,
    BusinessEndTime TIME NULL,
    IntervalMinutes INT NULL,
    AnalysisHoursJson JSON NULL,
    OutputTypesJson JSON NULL,
    IsEnabled TINYINT(1) NOT NULL DEFAULT 1,
    LastRunAt DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_stackctrl_schedule_company_key (CompanyID, ScheduleKey),
    KEY ix_stackctrl_schedule_enabled (CompanyID, IsEnabled, ScheduleType)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS StackCTRLIntelligenceScheduleRuns (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CompanyID BIGINT NOT NULL,
    ScheduleID BIGINT UNSIGNED NULL,
    ScheduleKey VARCHAR(100) NOT NULL,
    RunType VARCHAR(50) NOT NULL,
    TriggerType VARCHAR(50) NOT NULL,
    DeduplicationKey VARCHAR(255) NOT NULL,
    ParentRunID BIGINT UNSIGNED NULL,
    RequestedOutputTypes JSON NULL,
    Status VARCHAR(50) NOT NULL DEFAULT 'started',
    SnapshotID BIGINT UNSIGNED NULL,
    IntelligenceRunID BIGINT UNSIGNED NULL,
    CollectionSummaryJson JSON NULL,
    HistoricalContextJson JSON NULL,
    ErrorMessage TEXT NULL,
    CreatedByUserID BIGINT NULL,
    CreatedByEmail VARCHAR(255) NULL,
    StartedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CompletedAt DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_stackctrl_schedule_run_dedupe (DeduplicationKey),
    KEY ix_stackctrl_schedule_runs_company_started (CompanyID, StartedAt),
    KEY ix_stackctrl_schedule_runs_status (Status, StartedAt),
    KEY ix_stackctrl_schedule_runs_schedule (ScheduleID, StartedAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
